export enum NpcAction {
    THEM_NPC_SPAWN = 'THEM_NPC_SPAWN',
    SUA_NPC_SPAWN = 'SUA_NPC_SPAWN',
    XOA_NPC_SPAWN = 'XOA_NPC_SPAWN',
    THEM_NPC_SHOP = 'THEM_NPC_SHOP',
    SUA_NPC_SHOP = 'SUA_NPC_SHOP',
    XOA_NPC_SHOP = 'XOA_NPC_SHOP'
}